### ISSUE TITLE
🔨REFACTIORING : props 이동

### ISSUE THREAD

**Issue by ohwowoAo** [shyneeds/shyneeds_FE#118]
## Description
MypageTab에서 Withdrawal로 props를 이동시켜 팝업창 on/off 구현

## 작업할 내용
- [x] interface사용해서 props 이동시키기

**Comment by Yupmac** [comment]
해결 방법을 알게 되면 공유 부탁합니다.

**Comment by ohwowoAo** [comment]
https://velog.io/@ohwowo_o/Interface%EB%A1%9C-props-%EC%9D%B4%EB%8F%99%ED%95%98%EA%B8%B0 참고하세요!
