### ISSUE TITLE
✨ FEAT : 라우터 설정

### ISSUE THREAD

**Issue by Youngpro95** [shyneeds/shyneeds_FE#25]
## Description
1. 라우터 설정 
   1.1 index.tsx에 BroswerRouter 설정
   1.2 App.tsx에 Routes 및 Route 설정
2. 라우팅된 Path가 아닐시 보여주는 간단한 Error 페이지

## ETC
추후 
ex ) pages/etc... 폴더에 컴포넌트들 모아주신후 
app.tsx에 import 시켜서 route 설정 부탁드립니다.

**Comment by Yupmac** [comment]
확인
